apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: openshift-uninstall
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tags:
    displayName: "openshift uninstall"
spec:
  description: >-
    The following task helps you to provision the Openshift cluster using the
    Installer Provided Infrastructure on the desired cloud platform.

  workspaces:
    - name: install-dir
      mountPath: "/tekton/home/"
  steps:
    - name: remove-cluster
      image: quay.io/openshift/origin-upi-installer:4.4
      workingDir: $(workspaces.install-dir.path)
      script: |
        #!/usr/bin/env bash

        echo "Trying to delete the cluster"
        timeout 30m /bin/openshift-install destroy cluster --log-level=debug || true
      securityContext:
        runAsUser: 0
