apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kubeval
  annotations:
    tags: test
    version: "0.1"
    displayName: "kubeval"
spec:
  description: >-
    This task makes it possible to use Kubeval within your Tekton pipelines.

    Kubeval is a tool used for validating Kubernetes configuration files. By
    default the task will recursively scan the provided repository for YAML
    files and validate them against the Kubernetes schemas.

  workspaces:
    - name: source
  params:
    - name: files
      default: "."
    - name: output
      default: "stdout"
    - name: args
      type: array
      default: []

  steps:
    - name: kubeval
      workingDir: $(workspaces.source.path)
      image: garethr/kubeval:latest
      command:
        - kubeval
        - -d
        - $(params.files)
        - -o
        - $(params.output)
        - $(params.args)
